# Generated by Django 4.2.3 on 2023-08-06 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_name',
        ),
        migrations.AddField(
            model_name='activity',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.account'),
        ),
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
